#yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
- name: Install Redis Repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: yes

#dnf module enable redis:remi-6.2 -y
#yum install redis -y
- name: Enable & Install redis repo file
  ansible.builtin.dnf:
    name: "@redis:remi-6.2"
    state: installed

#Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/redis.conf & /etc/redis/redis.conf
- name: Update Redis Listening port
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: "127.0.0.1"
    replace: "0.0.0.0"

#systemctl enable redis
#systemctl start redis
- name: Start Redis
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: true