# yum install nginx -y

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

# rm -rf /usr/share/nginx/html/*

- name: Remove old html content of nginx
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create application Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#- name: Download and Extact frontend content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

## download app content from nexus artifact
- name: Download and extract {{ component }} content
  ansible.builtin.unarchive:
    src: http://{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.username', region = 'us-east-1') }}:{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.password', region = 'us-east-1') }}@nexus.devopspract.online:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /usr/share/nginx/html
    remote_src: yes

# configuration file is updated new log format is created
- name: Create Nginx configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Create Roboshop config in Nginx
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

#  systemctl restart nginx
- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes